name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Delete drafts
        uses: hugo19941994/delete-draft-releases@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: true
          name: latest
          files: |
            dist/**/*
#       - name: backup files
#         run: |
#           git rev-parse HEAD > dist/commit.txt
#           mv dist __dist__
#       - name: Checkout
#         uses: actions/checkout@v2
#         with:
#           clean: false
#           ref: latest
#       - name: Commit files
#         run: |
#           rm -rf dist
#           mv __dist__ dist
          
#           git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
#           git config --local user.name "github-actions[bot]"
#           git add dist
#           git commit -m "update dist"
#       - name: Push changes
#         uses: ad-m/github-push-action@master
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           branch: latest
