
name: OpenSSL

on:
  workflow_dispatch: # manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: log env
        run: |
          echo "GET /" | openssl s_client -showcerts -servername dcc.coronawarn.app -connect dcc.coronawarn.app:443
