

name: Random

on:
  workflow_dispatch: # manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: random number
        run: |
          echo "SOME_NUMBER=$(( $RANDOM % 100 + 1 ))" >> $GITHUB_ENV
      - name: log env
        run: |
          echo $SOME_NUMBER
      - name: say a
        if: ${{ env.SOME_NUMBER > 50 }}
        run: |
          echo "A"
      - name: say b
        if: ${{ env.SOME_NUMBER <= 50 }}
        run: |
          echo "B"
#         env:
#           aNumber: ${{ Math.random() }}
